services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.crt:/etc/nginx/ssl/localhost.crt
      - ./localhost.key:/etc/nginx/ssl/localhost.key
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - app
      - api
  app:
    build:
      context: .
      dockerfile: ./packages/app/Dockerfile
    environment:
      NODE_ENV: development
    expose:
      - 5173
    develop:
      watch:
        - path: ./packages/app/package.json
          action: rebuild
        - path: ./packages/app/Dockerfile
          action: rebuild
        - path: ./packages/app
          target: ./app/packages/app
          action: sync
        - path: ./packages/shared
          target: ./app/packages/shared
          action: sync
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    environment:
      NODE_ENV: development
    expose:
      - 3000
    develop:
      watch:
        - path: ./packages/api/package.json
          action: rebuild
        - path: ./packages/api/Dockerfile
          action: rebuild
        - path: ./packages/api
          target: ./app/packages/api
          action: sync
        - path: ./packages/shared
          target: ./app/packages/shared
          action: sync
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data:
